# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='liked_books', to='book_app.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=None),
        ),
    ]
