# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20170816_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_books', to='book_app.User'),
        ),
    ]
